# Welcome to Jekyll!

# Website settings
title: pgyogesh
description: My CV at https://pgyogesh.github.io/cv
keywords: Yogesh Jadhav,cv,resume
baseurl:  /cv
url: https://pgyogesh.github.io/cv
# url: http://127.0.0.1:4000

# baidu analytics
ba:
  uuid: 317acca9ef9255b934e46371e471431d

# Build settings
encoding: utf-8

gems:
  - jekyll-relative-links
relative_links:
  enabled:     true

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
